# Generated by Django 5.1 on 2024-10-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.JSONField(),
        ),
    ]
