# Generated by Django 5.1 on 2024-10-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_alter_problem_sample_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='sample_output',
            field=models.JSONField(),
        ),
    ]
