# Generated by Django 5.1 on 2024-10-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_remove_problem_problem_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.JSONField(),
        ),
    ]
