# Generated by Django 5.1 on 2024-10-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0008_userprofile_solved_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
