# Generated by Django 5.1 on 2024-11-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0009_userprofile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(choices=[('python3', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('csharp', 'C#')], max_length=50),
        ),
    ]
