# Generated by Django 5.1 on 2024-11-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0010_alter_codesnippet_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(blank=True, choices=[('python3', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('csharp', 'C#')], max_length=50, null=True),
        ),
    ]
