# Generated by Django 5.1 on 2024-11-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0011_submission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_output',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
