# Generated by Django 5.1 on 2024-11-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0012_alter_problem_sample_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
