# Generated by Django 5.1 on 2024-11-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='institue',
        ),
    ]
