# Generated by Django 5.1 on 2025-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0003_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='institue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
